/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Chart: typeof import('primevue/chart')['default']
    ClassificationTable: typeof import('./src/components/competitions/classification/ClassificationTable.vue')['default']
    Column: typeof import('primevue/column')['default']
    CompetitionCarousel: typeof import('./src/components/dashboard/CompetitionCarousel.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    copy: typeof import('./src/components/competitions/team/matchStats copy.vue')['default']
    CreateOrEditCompetition: typeof import('./src/components/dialogs/CreateOrEditCompetition.vue')['default']
    CreateOrEditTeam: typeof import('./src/components/dialogs/CreateOrEditTeam.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeleteDialog: typeof import('./src/components/dialogs/DeleteDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    GoalStats: typeof import('./src/components/competitions/team/goalStats.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MatchStats: typeof import('./src/components/competitions/team/matchStats.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MostTrashed: typeof import('./src/components/competitions/summary/MostTrashed.vue')['default']
    Password: typeof import('primevue/password')['default']
    PositionStats: typeof import('./src/components/competitions/team/positionStats.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RoundMatch: typeof import('./src/components/competitions/results/RoundMatch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SpeedDial: typeof import('primevue/speeddial')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    TeamCarousel: typeof import('./src/components/dashboard/TeamCarousel.vue')['default']
    TeamMatchList: typeof import('./src/components/competitions/team/teamMatchList.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    TopDifference: typeof import('./src/components/competitions/summary/TopDifference.vue')['default']
    TopScorers: typeof import('./src/components/competitions/summary/TopScorers.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
