version: '3.8'

services:
  matchanalyzer-front:
    image: ghcr.io/manelmendez/matchanalyzer-front/matchanalyzer-front:latest
    container_name: "matchanalyzer-front"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./dist:/var/www/html
    networks:
      - matchanalyzer_ma_backend
networks:
  matchanalyzer_ma_backend:
    external: true
